apiVersion: apps/v1
kind: Deployment
metadata:
  name: section13-es3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: section13-es3
  template:
    metadata:
      labels:
        app: section13-es3
    spec:
      volumes:
        - name: section13-es3-data
          persistentVolumeClaim:
            claimName: section13-es3-claim
      containers:
        - name: node
          image: giammarcoboscaro/kubernetes-course:section13-es3
          env:
            - name: FOLDER_NAME
              valueFrom:
                configMapKeyRef:
                  name: section13-es3-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story # container internal path
              name: section13-es3-data
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"              
