apiVersion: apps/v1
### DEPLOYMENT ###
kind: Deployment
metadata:
  name: section12-es2-deployment
  labels:
      group: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: es2
      tier: backend
  template:
    ### POD ###
    metadata:
      labels:
        app: es2
        tier: backend
    spec: 
      containers:
        - name: node
          image: giammarcoboscaro/kubernetes-course:section12-es1
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 3
            initialDelaySeconds: 10
              # httpHeaders:
              #   - 
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"              
        # - name: ...
        #   image: ...
    ### POD END ###
### DEPLOYMENT END ###
