apiVersion: v1
kind: Service
metadata:
  name: section12-es2-service
  labels:
      group: example
spec:
  selector: 
    app: es2
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer