apiVersion: apps/v1
kind: Deployment
metadata:
  name: section13-es1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: section13-es1
  template:
    metadata:
      labels:
        app: section13-es1
    spec:
      volumes:
        - name: section13-es1-data
          # emptyDir: {} # default setting
          hostPath:
            path: /data # path in the host machine
            type: DirectoryOrCreate
      containers:
        - name: node
          image: giammarcoboscaro/kubernetes-course:section13-es1-v2
          volumeMounts:
            - mountPath: /app/story # container internal path
              name: section13-es1-data
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"              
