apiVersion: v1
kind: Service
metadata:
  name: section13-es1-service
spec:
  selector: 
    app: section13-es1
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 3000
  type: LoadBalancer