apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-deployment
        image: giammarcoboscaro/kubernetes-course:section14-es4-frontend
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
