apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users-deployment
        image: giammarcoboscaro/kubernetes-course:section14-es2-users
        env:
          - name: AUTH_ADDRESS
            value: "auth-service.default"
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
